# Generated by Django 6.0.5 on 2026-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
