# Generated by Django 6.0.5 on 2026-06-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='featured_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shops.featuredcategory'),
        ),
    ]
